# Generated by Django 4.0.2 on 2023-02-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=500)),
                ('userAccessToken', models.CharField(max_length=500)),
                ('summaryId', models.CharField(max_length=500)),
                ('calendarDate', models.DateField()),
                ('activeKilocalories', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('durationinSeconds', models.IntegerField()),
                ('startTimelnSeconds', models.IntegerField()),
                ('startTimeOffsetInSeconds', models.IntegerField()),
                ('minHeartRatelnBeatsPerMinute', models.IntegerField()),
                ('maxHeartRateInBeatsPerMinute', models.IntegerField()),
                ('averageHeartRatelnBeatsPerMinute', models.IntegerField()),
                ('restingHeartRatelnBeatsPerMinute', models.IntegerField()),
                ('maxStressLevel', models.IntegerField()),
                ('lowStressDurationInSeconds', models.IntegerField()),
                ('mediumStressDurationinSeconds', models.IntegerField()),
                ('highStressDurationInSeconds', models.IntegerField()),
                ('stressQualifier', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=500)),
                ('userAccessToken', models.CharField(max_length=500)),
                ('summaryId', models.CharField(max_length=500)),
                ('calendarDate', models.DateField()),
                ('durationInSeconds', models.IntegerField()),
                ('overallSleepScorevalue', models.IntegerField()),
                ('overallSleepScorequalifierKey', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
