# Generated by Django 4.0.2 on 2023-02-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0002_dailydata_sleepdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sleepdata',
            unique_together={('userid', 'userAccessToken', 'calendarDate')},
        ),
        migrations.AlterIndexTogether(
            name='sleepdata',
            index_together={('userid', 'userAccessToken', 'calendarDate')},
        ),
    ]
