# Generated by Django 4.0.2 on 2023-02-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0003_alter_sleepdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together={('userid', 'userAccessToken', 'calendarDate')},
        ),
        migrations.AlterIndexTogether(
            name='dailydata',
            index_together={('userid', 'userAccessToken', 'calendarDate')},
        ),
    ]
