# Generated by Django 4.0.2 on 2023-02-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0004_alter_dailydata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sleepdata',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='dailydata',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='sleepdata',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sleepdata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
