# Generated by Django 4.0.2 on 2023-02-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0005_alter_dailydata_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydata',
            old_name='averageHeartRatelnBeatsPerMinute',
            new_name='averageHeartRateInBeatsPerMinute',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='durationinSeconds',
            new_name='durationInSeconds',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='mediumStressDurationinSeconds',
            new_name='mediumStressDurationInSeconds',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='minHeartRatelnBeatsPerMinute',
            new_name='minHeartRateInBeatsPerMinute',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='restingHeartRatelnBeatsPerMinute',
            new_name='restingHeartRateInBeatsPerMinute',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='startTimelnSeconds',
            new_name='startTimeInSeconds',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='userid',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='sleepdata',
            old_name='userid',
            new_name='userId',
        ),
    ]
