# Generated by Django 4.0.2 on 2023-02-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0006_rename_averageheartratelnbeatsperminute_dailydata_averageheartrateinbeatsperminute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='activityStressDurationInSeconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='highStressDurationInSeconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='lowStressDurationInSeconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='maxStressLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='mediumStressDurationInSeconds',
            field=models.IntegerField(null=True),
        ),
    ]
