# Generated by Django 4.0.2 on 2023-02-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0007_dailydata_activitystressdurationinseconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepdata',
            name='durationInSeconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sleepdata',
            name='overallSleepScorevalue',
            field=models.IntegerField(null=True),
        ),
    ]
