# Generated by Django 4.0.2 on 2023-02-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0008_alter_sleepdata_durationinseconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='activeKilocalories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='averageHeartRateInBeatsPerMinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='durationInSeconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='maxHeartRateInBeatsPerMinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='minHeartRateInBeatsPerMinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='restingHeartRateInBeatsPerMinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='startTimeInSeconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='startTimeOffsetInSeconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='stressQualifier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sleepdata',
            name='overallSleepScorequalifierKey',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
