# Generated by Django 4.0.2 on 2023-03-11 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wearable', '0009_alter_dailydata_activekilocalories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydata',
            old_name='userId',
            new_name='garminUserId',
        ),
        migrations.RenameField(
            model_name='sleepdata',
            old_name='userId',
            new_name='garminUserId',
        ),
        migrations.CreateModel(
            name='UserIdMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garminUserId', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
