# Generated by Django 3.2.7 on 2021-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
