# Generated by Django 3.2.7 on 2022-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(default='This text has not been set (we will be tracking text for newer notifications)', max_length=300),
            preserve_default=False,
        ),
    ]
