# Generated by Django 4.0.2 on 2022-11-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='survey',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
