# Generated by Django 4.0.2 on 2023-01-19 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
