# Generated by Django 4.0.2 on 2023-02-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post_comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post_like',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='show',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='survey',
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('post', 'post'), ('comment', 'comment'), ('like', 'like'), ('survey', 'survey'), ('reminder', 'reminder')], max_length=100),
        ),
    ]
