# Generated by Django 4.0.2 on 2023-02-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_notification_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
