# Generated by Django 4.0.2 on 2023-02-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_rename_text_notification_title_notification_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_on',
        ),
    ]
