# Generated by Django 4.0.2 on 2023-02-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_remove_notification_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_object',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
