# Generated by Django 4.0.2 on 2022-02-28 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='reason',
            field=models.TextField(default='Default reason for sending this recommendation'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='labels',
            unique_together={('name', 'type', 'reason')},
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('label', 'user')},
        ),
    ]
