# Generated by Django 4.0.2 on 2022-02-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_labels_reason_alter_labels_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='link',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
