# Generated by Django 4.0.2 on 2022-02-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_labels_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='is_label',
            field=models.BooleanField(default=True),
        ),
    ]
