# Generated by Django 4.0.2 on 2022-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_labels_is_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='is_label',
            field=models.BooleanField(default=True),
        ),
    ]
