# Generated by Django 4.0.2 on 2022-03-21 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postcomment_link'),
        ('recommendations', '0006_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.postcomment'),
            preserve_default=False,
        ),
    ]
