# Generated by Django 4.0.2 on 2022-03-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_tracker_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='is_coupuled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='labels',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
