# Generated by Django 4.0.2 on 2022-03-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_tracker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='labelType_scores',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='label_scores',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
