# Generated by Django 3.2.7 on 2022-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_tracker_labeltype_scores_tracker_label_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.TextField(),
        ),
    ]
