# Generated by Django 4.0.2 on 2022-11-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0011_alter_labels_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ratings',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
