# Generated by Django 4.0.2 on 2022-11-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0012_alter_ratings_unique_together_ratings_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
