# Generated by Django 4.0.2 on 2023-01-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_groups_image'),
        ('posts', '0008_alter_post_link'),
        ('recommendations', '0013_ratings_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='labelType_scores',
            new_name='estimated_couple_ratings',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='label_scores',
            new_name='estimated_final_recommendation_list',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='recommendation_tree',
            new_name='estimated_rating_for_context_dic',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='label',
        ),
        migrations.AddField(
            model_name='tracker',
            name='estimated_raw_ratings_withoutcontext',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='nlp_raw_outputs',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='recommended_label',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GroupRecommendationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelType_scores', models.TextField()),
                ('label_scores', models.TextField()),
                ('recommendation_tree', models.TextField()),
                ('nlp_classification', models.TextField(max_length=100)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postcomment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.labels')),
            ],
        ),
    ]
