# Generated by Django 4.0.2 on 2023-01-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_is_recommendation_post_need_feadback'),
        ('groups', '0006_alter_groups_image'),
        ('recommendations', '0014_rename_labeltype_scores_tracker_estimated_couple_ratings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRecommendationInitalizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=300)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_scores', models.TextField()),
                ('recommendation_tree', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('recommended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.labels')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupRecommendationTracker',
        ),
    ]
