# Generated by Django 4.0.2 on 2023-01-08 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0015_grouprecommendationinitalizer_grouptracker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptracker',
            old_name='label_scores',
            new_name='recommendation_scores',
        ),
        migrations.AddField(
            model_name='grouprecommendationinitalizer',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
