# Generated by Django 4.0.2 on 2023-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0016_rename_label_scores_grouptracker_recommendation_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprecommendationinitalizer',
            name='date_time',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
