# Generated by Django 4.0.2 on 2023-01-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0017_alter_grouprecommendationinitalizer_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprecommendationinitalizer',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
