# Generated by Django 4.0.2 on 2023-01-08 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_groups_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_post_is_recommendation_post_need_feadback'),
        ('recommendations', '0018_alter_grouprecommendationinitalizer_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupRecommendationInitalizer',
            new_name='SenderGroupRecommendation',
        ),
        migrations.RenameModel(
            old_name='GroupTracker',
            new_name='TrackerGroupRecommendation',
        ),
        migrations.RenameModel(
            old_name='Tracker',
            new_name='TrackerPostRecommendation',
        ),
        migrations.CreateModel(
            name='SenderPostRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
