# Generated by Django 4.0.2 on 2023-01-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0019_rename_grouprecommendationinitalizer_sendergrouprecommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerpostrecommendation',
            name='recommended',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommendations.labels'),
            preserve_default=False,
        ),
    ]
