# Generated by Django 4.0.2 on 2023-01-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0020_trackerpostrecommendation_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerpostrecommendation',
            name='recommended_label',
        ),
    ]
