# Generated by Django 4.0.2 on 2023-01-08 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0021_remove_trackerpostrecommendation_recommended_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackergrouprecommendation',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommendations.sendergrouprecommendation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerpostrecommendation',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommendations.senderpostrecommendation'),
            preserve_default=False,
        ),
    ]
