# Generated by Django 4.0.2 on 2023-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0023_trackergrouprecommendation_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackergrouprecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('source', 'source'), ('social', 'social'), ('hybread', 'hybread')], default='hybread', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerpostrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('source', 'source'), ('social', 'social'), ('hybread', 'hybread')], default='hybread', max_length=100),
            preserve_default=False,
        ),
    ]
