# Generated by Django 4.0.2 on 2023-01-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_configuration_date_time'),
        ('recommendations', '0024_trackergrouprecommendation_recommendation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackergrouprecommendation',
            name='configurations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuration.configuration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerpostrecommendation',
            name='configurations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuration.configuration'),
            preserve_default=False,
        ),
    ]
