# Generated by Django 4.0.2 on 2023-01-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_groups_date_time_groupsmember_date_time'),
        ('recommendations', '0025_trackergrouprecommendation_configurations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledGroupTaslk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('done_today', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
            ],
        ),
    ]
