# Generated by Django 4.0.2 on 2023-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0026_scheduledgrouptaslk'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='hybrid_based',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labels',
            name='social_based',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labels',
            name='source_based',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
    ]
