# Generated by Django 4.0.2 on 2023-03-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_groups_date_time_groupsmember_date_time'),
        ('posts', '0011_commentfeedback_date_time_postcomment_date_time_and_more'),
        ('configuration', '0003_configuration_date_time'),
        ('recommendations', '0026_scheduledgrouptaslk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerWearableRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_tree', models.TextField()),
                ('recommendation_scores', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('recommendation_type', models.CharField(choices=[('source', 'source'), ('social', 'social'), ('hybread', 'hybread')], max_length=100)),
                ('configurations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.configuration')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('recommended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.labels')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.sendergrouprecommendation')),
            ],
        ),
        migrations.CreateModel(
            name='SenderWearableRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=3000)),
                ('sleep', models.FloatField(null=True)),
                ('stress', models.FloatField(null=True)),
                ('food', models.FloatField(null=True)),
                ('exercise', models.FloatField(null=True)),
                ('general', models.FloatField(null=True)),
                ('tags', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
            ],
        ),
    ]
