# Generated by Django 4.0.2 on 2023-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0027_labels_hybrid_based_labels_social_based_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='group_based',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
    ]
