# Generated by Django 4.0.2 on 2023-03-12 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0027_trackerwearablerecommendation_and_more'),
        ('recommendations', '0028_labels_group_based'),
    ]

    operations = [
    ]
