# Generated by Django 4.0.2 on 2023-03-13 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0029_merge_20230312_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderwearablerecommendation',
            name='group',
        ),
        migrations.AddField(
            model_name='senderwearablerecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
