# Generated by Django 4.0.2 on 2023-03-13 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0030_remove_senderwearablerecommendation_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerwearablerecommendation',
            name='group',
        ),
        migrations.AddField(
            model_name='trackerwearablerecommendation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
