# Generated by Django 4.0.2 on 2023-03-14 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0031_remove_trackerwearablerecommendation_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerwearablerecommendation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.senderwearablerecommendation'),
        ),
    ]
