# Generated by Django 4.0.2 on 2023-05-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0032_alter_trackerwearablerecommendation_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderwearablerecommendation',
            name='general',
        ),
        migrations.AddField(
            model_name='senderwearablerecommendation',
            name='optimal',
            field=models.BooleanField(default=False),
        ),
    ]
