# Generated by Django 3.2.7 on 2021-09-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='devicename',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='token',
            new_name='devicetoken',
        ),
    ]
