# Generated by Django 4.0.2 on 2023-01-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
