"""
Django settings for Social_API project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',

    'accounts',
    'groups',
    'posts',
    'notifications',
    'recommendations',
    'configuration',
    'wearable',
]

AUTHENTICATION_BACKENDS = ['Social_API.midware.EmailOrUsernameModelBackend', ]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'Social_API.authentication.DeviceAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'Social_API.midware.DisableCSRFMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Social_API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Social_API.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= Path(BASE_DIR, "static")

MEDIA_URL= '/media/'
MEDIA_ROOT= Path(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PROJECT_NAME = 'PhamilyHealth'

FIREBASE_PROJECT_KEY= 'AAAARVQhCgA:APA91bGemTw3miRbIQtYgIG1LbgG1Fxc7JkTPlZzP51d9uLnDWIMhQTK186WfkfY1rJHIll-mGnCd-r7gqhhUM_PlW4asnjrJd-QyptD1_vOicjK0LbdlUOQPOsbh6vFmuB62-53YI_k'

MODELS_PATH = Path(BASE_DIR, 'models/best_model-xlnet-base-cased')
MODEL_NAME = 'xlnet'

import os

os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
BOT_ID = 4

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # This will chek for all scheduled tasks. It will run every 120 seconds
    'Scheduled-Recommendations': {
        'task': 'recommendations.tasks.runScheduledTasks',
        'schedule': 120.0,
    },
    # This will set scheduled tasks 'date_time' parameter to false, so it can run for the next day
    'Reset-Scheduled': {
        'task': 'recommendations.tasks.resetScheduledTasks',
        'schedule':crontab(minute=0, hour=0),
    }
}