# Generated by Django 3.2.7 on 2021-09-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='name',
            new_name='group_name',
        ),
    ]
