# Generated by Django 4.0.2 on 2022-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_name_groups_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='gtype',
            field=models.CharField(choices=[('Default', 'Default'), ('Channel', 'Channel')], default='Default', max_length=20),
        ),
    ]
