# Generated by Django 3.2.7 on 2021-09-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupsmember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsmember',
            old_name='team',
            new_name='groups',
        ),
    ]
