# Generated by Django 4.0.2 on 2022-06-13 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_groups_gtype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsmember',
            unique_together={('group', 'user')},
        ),
    ]
