# Generated by Django 3.2.7 on 2022-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groupsmember_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='image',
            field=models.ImageField(default='media/media/image/default_profile.jpg', upload_to=''),
        ),
    ]
