# Generated by Django 3.2.7 on 2022-06-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groups_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.ImageField(default='media/image/default_profile.jpg', upload_to='groups'),
        ),
    ]
