# Generated by Django 4.0.2 on 2023-03-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_groups_date_time_groupsmember_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
