# Generated by Django 3.2.7 on 2021-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_team_groupsmember_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsmember',
            old_name='groups',
            new_name='group',
        ),
    ]
