from django.conf import settings
from django.contrib.auth import get_user_model
from groups.models import GroupsMember
from notifications.models import Notification
from recommendations.models import SenderPostRecommendation, Ratings
from configuration.models import Configuration


User = get_user_model()

def postCreatedNotification(sender, instance, created, **kwargs):        
    if not created:
        # If not a new post
        return

    # Sending recommendation
    SenderPostRecommendation.objects.create(post=instance, tags="Autogenerated")

    # Sending notification
    group_members = GroupsMember.objects.filter(group=instance.group).exclude(user=instance.user)
    notifications = []
    for group_member in group_members:
        Notification.objects.create(user=group_member.user, post=instance, post_comment=None, post_like=None, text=str(instance.user.username)+" created a new post")


def commentCreatedNotification(sender, instance, created, **kwargs):
    if not created:
        return

    # If a new post is created 
    group_members = GroupsMember.objects.filter(group=instance.post.group).exclude(user=instance.user)
    notifications = []
    for group_member in group_members:
        Notification.objects.create(user=group_member.user, post=instance.post, post_comment=instance, post_like=None, text=str(instance.user.username)+" commented on a post")


def likeCreatedNotification(sender, instance, created, **kwargs):
    if not created:
        return

    # If a new post is created 
    group_members = GroupsMember.objects.filter(group=instance.post.group, user=instance.post.user).exclude(user=instance.user)
    notifications = []
    for group_member in group_members:
        Notification.objects.create(user=group_member.user, post=instance.post, post_comment=None, post_like=instance, text=str(instance.user.username)+" liked a post")

def feadbackCreates(sender, instance, created, **kwargs):    
    for obj in Ratings.objects.filter(user=instance.user, label=instance.comment.label, is_active=True):
        obj.is_active = False
        obj.save()
    Ratings.objects.create(label=instance.comment.label, user=instance.user, rating=instance.rating)
 