# Generated by Django 3.2.7 on 2021-09-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_team_post_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='tt',
        ),
    ]
