# Generated by Django 3.2.7 on 2022-02-24 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_commentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfeedback',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='commentfeedback',
            unique_together={('comment', 'user')},
        ),
    ]
