# Generated by Django 3.2.7 on 2021-09-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_group_post_tt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tt',
            new_name='group',
        ),
    ]
