# Generated by Django 4.0.2 on 2022-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220224_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
