# Generated by Django 4.0.2 on 2022-03-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postcomment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_bot',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
