# Generated by Django 4.0.2 on 2022-03-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcomment_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='is_bot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
