# Generated by Django 4.0.2 on 2022-09-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postcomment_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
