# Generated by Django 4.0.2 on 2023-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_recommendation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='need_feadback',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
