# Generated by Django 4.0.2 on 2023-01-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0022_trackergrouprecommendation_sender_and_more'),
        ('posts', '0009_post_is_recommendation_post_need_feadback'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.labels'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.labels'),
        ),
    ]
